# Generated by Django 3.0.5 on 2022-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, null=True)),
                ('femail', models.CharField(max_length=20, null=True)),
                ('fcontact', models.CharField(max_length=20, null=True)),
                ('feedback', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
