# Generated by Django 3.0.5 on 2022-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20, null=True)),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('contact1', models.CharField(max_length=30, null=True)),
                ('contact2', models.CharField(max_length=30, null=True)),
                ('booking_date', models.CharField(max_length=30, null=True)),
                ('days', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('dob', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
